name: Jake Comics Site
favicon: null
layout_spectrum: 0.50414
typography_spectrum: 0.2796205645427108
title: Jake Comics Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#80cd96'
    - '#584054'
    - '#798664'
  brandStrength: 0.375
  lightness: 0.7907504099421203
  saturation: 0.6875
  rhythmicContrast: 0.23253394686616957
purpose: []
